---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    io.kompose.service: db
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --init-connect=SET NAMES UTF8;
        - --innodb-flush-log-at-trx-commit=0
        env:
        - name: MYSQL_DATABASE
          value: portus_production
        - name: MYSQL_ROOT_PASSWORD
          value: aFSxSWyThGYirYK7
        image: library/mariadb:10.0.23
        name: db
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
      restartPolicy: Always
      volumes:
      - name: db-data
        hostPath:
          path: /tmp/portus/mysql
