---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: docker-registry
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/docker/registry/
          name: config
        - mountPath: /data
          name: data
        - name: registry-cert-cm
          mountPath: /opt/certs/server.crt
          subPath: server.crt
          readOnly: false
        - name: registry-key-cm
          mountPath: /opt/certs/server.key
          subPath: server.key
          readOnly: false
      volumes:
      - hostPath:
          path: /tmp/docker-registry/data
        name: data
      - hostPath:
          path: /tmp/docker-registry/config
        name: config
      - name: registry-cert-cm
        configMap:
          name: registry-crt
      - name: registry-key-cm
        configMap:
          name: registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  ports:
  - name: http
    port: 30006
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    layer: L4
    protocol: tcp
  name: docker-registry
spec:
  backend:
    serviceName: docker-registry
    servicePort: 30006
