# . See reference.yml for explanation for explanation of all options.
#
#  auth:
#    token:
#      realm: "https://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"

server:
  addr: ":5001"
  certificate: "/certs/server.crt"
  key: "/certs/server.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

# LDAP authentication.
# Authentication is performed by first binding to the server, looking up the user entry
# by using the specified filter, and then re-binding using the matched DN and the password provided.
ldap_auth:
  addr: "docker.registry.com:30004"
  #tls: true
  # In case bind DN and password is required for querying user information,
  # specify them here. Plain text password is read from the file.
  bind_dn: "cn=admin,dc=example,dc=com"
  # Make sure you remove newlines and carriage returns from the password file.
  bind_password_file: /tmp/ldap_password.txt.clean
  # User query settings. ${account} is expanded from auth request
  base: "dc=example,dc=com"
  filter: "(&(uid=${account})(objectClass=organizationalPerson))"
  labels:
    groups:
      attribute: memberOf
      parse_cn: true

users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "test":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]

  # User "user" can pull and push to NSC namespace.
  - match: {account: "test", name: "pradeep/*"}
    actions: ["*"]

  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in their 'namespace'"

  - match: {account: "/.+/", name: "${labels:groups}/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in the group which they are belong to"

  - match: {account: "/.+/", name: "pradeep/*"}
    actions: ["pull"]
    comment: "Logged in users have full access to images that are in their 'namespace'"

  # The user "serviceaccount" (from LDAP) may not perform any docker actions
  # like push or pull.
  - match: {account: "serviceaccount"}
    actions: []

