---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: webui
  name: webui
spec:
  ports:
  - port: 30010
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: webui
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    layer: L4
    protocol: tcp
  name: webui
spec:
  backend:
    serviceName: webui
    servicePort: 30010
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: webui
    spec:
      containers:
      - env:
        - name: DOCKER_REGISTRY_URL
          value: https://137.58.180.216:30009
        - name: ENABLE_DELETE_IMAGES
          value: "true"
        - name: NO_SSL_VERIFICATION
          value: "true"
        - name: TOKEN_AUTH_USER
          value: dockeruser
        - name: TOKEN_AUTH_PASSWORD
          value: dockerpassword
        image: klausmeyer/docker-registry-browser
        name: webui
        ports:
        - containerPort: 8080
          name: webui
        resources: {}
      restartPolicy: Always
