---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: docker-registry
        ports:
        - containerPort: 443
          name: http
          protocol: TCP
        env:
        - name: REGISTRY_AUTH
          value: "token"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/data"
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:443"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/opt/certs/server.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/opt/certs/server.key"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: "/opt/certs/trust_chain.pem"
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: "http://docker.registry.com:30005/auth/realms/docker-registry/protocol/docker-v2/auth"
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "docker-registry-test"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "http://docker.registry.com:30005/auth/realms/docker-registry"
        volumeMounts:
        - mountPath: /etc/docker/registry/
          name: config
        - mountPath: /data
          name: data
        - name: registry-cert-cm
          mountPath: /opt/certs/server.crt
          subPath: server.crt
          readOnly: false
        - name: registry-key-cm
          mountPath: /opt/certs/server.key
          subPath: server.key
          readOnly: false
        - name: trust-chain-pem-cm
          mountPath: /opt/certs/trust_chain.pem
          subPath: trust_chain.pem
          readOnly: false
      volumes:
      - hostPath:
          path: /tmp/docker-registry/data
        name: data
      - hostPath:
          path: /tmp/docker-registry/config
        name: config
      - name: registry-cert-cm
        configMap:
          name: registry-crt
      - name: registry-key-cm
        configMap:
          name: registry-key
      - name: trust-chain-pem-cm
        configMap:
          name: trust-chain-pem
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  ports:
  - name: http
    port: 30006
    protocol: TCP
    targetPort: 443
  selector:
    app: docker-registry
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    layer: L4
    protocol: tcp
  name: docker-registry
spec:
  backend:
    serviceName: docker-registry
    servicePort: 30006
