---
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: scullog
        image: scullog:root
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value : "value"
        effect: "NoSchedule"
    metadata:
      labels:
        app: scullog
  replicas: 1
apiVersion: extensions/v1beta1
metadata:
  name: scullog
