---
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: http
    port: 30011
    targetPort: 8080
  selector:
    app: scullog
apiVersion: v1
metadata:
  name: scullog
---
kind: Deployment
spec:
  template:
    spec:
      volumes:
      - persistentVolumeClaim:
          claimName: "logs"
        name: logs
      containers:
      - name: scullog
        image: scullog:pod_test
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: "/home/pradeepadm/scullog"
          name: logs
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value : "value"
        effect: "NoSchedule"
    metadata:
      labels:
        app: scullog
  replicas: 1
apiVersion: extensions/v1beta1
metadata:
  name: scullog
