---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app
  name: proxy-manager
spec:
  ports:
  - name: http80
    port: 30006
    protocol: TCP
    targetPort: 80
  - name: http81
    port: 30007
    protocol: TCP
    targetPort: 81
  - name: http443
    port: 30008
    protocol: TCP
    targetPort: 443
  selector:
    io.kompose.service: app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    layer: L4
    protocol: tcp
  name: proxy-manager
spec:
  backend:
    serviceName: proxy-manager
    servicePort: 30007
