version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:81:81
      - 0.0.0.0:443:443
    networks:
      - default
      - backend
    volumes:
      - /tmp/proxy-manager/config.json:/app/config/production.json
      - /tmp/proxy-manager/data:/data
      - /tmp/proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "joo2uab3seeNgahDe1"
      MYSQL_DATABASE: "nginxproxymanager"
      MYSQL_USER: "nginxproxymanager"
      MYSQL_PASSWORD: "opea7AoCe5oquoocei"
    volumes:
      - /tmp/proxy-manager/data/mysql:/var/lib/mysql
 
networks:
  backend:
    external: false
    driver: bridge
