apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: adtest1
spec:
  selector:
    matchLabels:
      run: sample-app
  replicas: 2
  template:
    metadata:
      labels:
        run: sample-app
    spec:
      containers:
        - name: sample-app
          image: gcr.io/google-samples/node-hello:1.0
          ports:
           - containerPort: 8080
