---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    #setup.dashboards.enabled: true
    #setup.template.enabled: true
    #setup.template.settings:
      #index.number_of_shards: 1
    #setup.kibana.host: 'kibana:30125'
    #setup.kibana.username: 'elastic'
    #setup.kibana.password: 'test1234'
    #filebeat.registry.flush: 60s
    filebeat.inputs:
    - type: log
      paths:
        - /pradeep/logs/test/*_access.log
      exclude_lines: ['^None$']
      tags: ["pradeep", "apigateway"]
      fields:
        component: pradeep
        service: apigateway
      fields_under_root: true
      multiline.type: pattern
      multiline.match: after
      multiline.negate: true
      multiline.pattern: '^\[*[0-9]{4}-[0-9]{2}-[0-9]{2}|^None$'
    processors:
      - add_tags:
          tags: [production]
          target: "environment"
      - drop_fields:
          fields: ["ecs", "host", "agent"]
    output.logstash:
      hosts: ['logstash:5044']
      username: "elastic"
      password: "test1234"
    #output.console:
      #pretty: true
    #output.file:
      #path: "/pradeep/logs/filebeat"
      #number_of_files: 500
      #filename: filebeat-out
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pradeep
                operator: In
                values:
                - mgmt
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.3.2
        args: [
          "-c", "/etc/filebeat.yml",
          "--path.data", "/pradeep/logs/filebeat/data",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: elknsc123
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 2.5Gi
            cpu: 50m
          requests:
            cpu: 50m
            memory: 2.5Gi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - mountPath: "/pradeep/logs/"
          name: pradeeplogs
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - persistentVolumeClaim:
          claimName: "pradeep-logs"
        name: pradeeplogs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
