---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gogs
    spec:
#      securityContext:
#        runAsUser: 121254
#        runAsGroup: 54540
      containers:
      - resources:
        name: gogs
        image: gogs/gogs:0.12
#        lifecycle:
#          postStart:
#            exec:
#              command: ["/bin/sh", "-c", "groupadd -g ${GID} ${GNAME} && useradd -u ${UID} -g ${GNAME} -d /home/${UNAME} -s /bin/sh -c 'Init user' ${UNAME}"]
        ports:
        - name: gogs-port
          containerPort: 3000
        env:
        - name: PUID
          value: "7160629"
        - name: PGID
          value: "64000"
#        - name: GID
#          value: "525252"
#        - name: GNAME
#          value: "users"
#        - name: UID
#          value: "12578"
#        - name: UNAME
#          value: "pradeep"
        volumeMounts:
        - mountPath: /data
          name: data
        - name: certs
          mountPath: /opt/certs/server.crt
          subPath: server.crt
        - name: certs
          mountPath: /opt/certs/server.key
          subPath: server.key
      volumes:
      - persistentVolumeClaim:
          claimName: "ci-cd"
        name: data
      - name: certs
        configMap:
          name: registry-certs
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  ports:
  - name: http
    port: 30102
    protocol: TCP
    targetPort: 3000
  selector:
    name: gogs
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    layer: L4
    protocol: tcp
  name: gogs
spec:
  backend:
    serviceName: gogs
    servicePort: 30102
